layout_spectrum: 0.9641577
color:
  saturation: 0.7903226
  brandStrength: 0.0304724
  lightness: 0.7096774
  rhythmicContrast: 0.8584229
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.6200717
name: Elibernstein
